# Generated by Django 4.2.11 on 2024-05-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_notification_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='requested_from',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
