# Generated by Django 4.2.11 on 2024-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_notification_requested_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
