# Generated by Django 4.2.11 on 2024-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_balance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British pounds'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='GBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British pounds'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3),
        ),
    ]
